const test=require('node:test');const assert=require('node:assert/strict');const os=require('node:os');
const {runAgent}=require('../src/core/agent.cjs');const {validateAction,Computer}=require('../src/core/computer.cjs');
const call=(name,args={})=>({role:'assistant',content:null,tool_calls:[{id:'call',type:'function',function:{name,arguments:JSON.stringify(args)}}]});
const base=()=>({provider:{tools:true},agent:{mode:'edit',system:'Help with the requested task.'},messages:[],signal:new AbortController().signal,emit:()=>{},approve:async()=>true});
test('projectless Computer mode exposes approved terminal commands and runs in the chosen directory',async()=>{
 let step=0,approved;await runAgent({...base(),terminalRoot:os.tmpdir(),approve:async a=>{approved=a;return true;},complete:async request=>{if(!step++){assert.deepEqual(request.tools.map(t=>t.function.name),['run_command']);assert.match(request.messages[0].content,/approved run_command/);return call('run_command',{command:'pwd',reason:'Check working directory'});}const result=JSON.parse(request.messages.find(m=>m.role==='tool').content);assert.equal(result.output.trim(),os.tmpdir());return {role:'assistant',content:'Done'};}});assert.equal(approved.projectPath,os.tmpdir());
});
test('read-only and disabled connections cannot acquire host or desktop tools',async()=>{for(const override of [{agent:{mode:'read',system:'Read'}},{provider:{tools:false}}])await runAgent({...base(),...override,terminalRoot:os.tmpdir(),computer:{},complete:async r=>{assert.deepEqual(r.tools,[]);return {role:'assistant',content:'No tools'};}});});
test('declined screenshot never captures or sends an image',async()=>{let step=0;await runAgent({...base(),computer:{screenshot:()=>assert.fail('Must not capture')},approve:async()=>false,complete:async r=>{if(!step++)return call('computer_screenshot');assert.ok(!JSON.stringify(r).includes('image_url'));assert.match(r.messages.find(m=>m.role==='tool').content,/declined/);return {role:'assistant',content:'Stopped'};}});});
test('approved screenshot reaches the model transiently, after all tool replies, never persisted',async()=>{let step=0;const events=[];await runAgent({...base(),computer:{screenshot:async()=>({image:'data:image/jpeg;base64,fixture',width:100,height:80})},emit:e=>events.push(e),complete:async r=>{if(!step++){const c=call('computer_screenshot');c.tool_calls.push({...c.tool_calls[0],id:'second'});return c;}assert.equal(r.messages[2].role,'tool');assert.equal(r.messages[3].role,'tool');assert.equal(r.messages[4].content[1].type,'image_url');return {role:'assistant',content:'Seen'};}});assert.ok(!JSON.stringify(events).includes('data:image'));});
test('desktop action is validated before approval and a declined action never executes',async()=>{let approved=0,step=0;await runAgent({...base(),computer:{action:()=>assert.fail('Must not execute')},approve:async()=>{approved++;return false;},complete:async()=>!step++?call('computer_action',{action:'click',x:-1,y:0}):{role:'assistant',content:'Invalid'}});assert.equal(approved,0);step=0;await runAgent({...base(),computer:{action:()=>assert.fail('Must not execute')},approve:async()=>false,complete:async()=>!step++?call('computer_action',{action:'click',x:1,y:2}):{role:'assistant',content:'Declined'}});});
test('computer action validation bounds inputs and rejects arbitrary key commands',()=>{assert.deepEqual(validateAction({action:'key',key:'CTRL+l'}),{action:'key',key:'CTRL+l'});assert.throws(()=>validateAction({action:'key',key:'exec bash'}));assert.throws(()=>validateAction({action:'type',text:'\x1b'}));assert.throws(()=>validateAction({action:'scroll',steps:999}));assert.throws(()=>validateAction({action:'click',x:Infinity,y:0}));assert.throws(()=>validateAction({action:'shell',command:'anything'}));});
test('disconnected computer does not start a helper for model actions',async()=>{const c=new Computer({spawnProcess:()=>assert.fail('Do not spawn')});await assert.rejects(c.action({action:'key',key:'Enter'}),/Connect/);await assert.rejects(c.screenshot(),/Connect/);});
