const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { Store } = require('../src/core/store.cjs');
const { Vault } = require('../src/core/vault.cjs');
const ws = require('../src/core/workspace.cjs');
const { runAgent } = require('../src/core/agent.cjs');
async function fixture(t) { const root = await fs.mkdtemp(path.join(os.tmpdir(), 'agent-studio-test-')); t.after(() => fs.rm(root, { recursive: true, force: true })); return root; }
const toolCall = (name, args) => ({ role: 'assistant', content: null, tool_calls: [{ id: 'call-1', type: 'function', function: { name, arguments: JSON.stringify(args) } }] });
function options(root, overrides = {}) { let index = 0; return { provider: {}, model: 'fixture-model', agent: { name: 'Test', mode: 'edit', system: 'Test' }, project: { path: root, name: 'fixture' }, messages: [{ role: 'user', content: 'Test task' }], signal: new AbortController().signal, emit() {}, approve: async () => true, complete: async () => index++ === 0 ? toolCall('write_file', { path: 'hello.txt', content: 'hello' }) : { role: 'assistant', content: 'Done' }, ...overrides }; }
test('workspace rejects traversal, absolute paths, secrets and symlinks', async t => { const root = await fixture(t); await fs.writeFile(path.join(root, 'ok.txt'), 'hello'); await fs.symlink('/tmp', path.join(root, 'escape')); for (const relative of ['../outside','/etc/passwd','.env','a/.env.local','secret.pem','escape/file']) await assert.rejects(ws.resolveSafe(root, relative, true)); assert.equal(await ws.readFile(root, 'ok.txt'), 'hello'); });
test('listing excludes secrets, binary reading is blocked, and search returns lines', async t => { const root = await fixture(t); await fs.writeFile(path.join(root, '.env'), 'secret'); await fs.writeFile(path.join(root, 'a.txt'), 'first\nneedle'); await fs.writeFile(path.join(root, 'binary'), Buffer.from([0,1])); assert.ok(!(await ws.listFiles(root)).some(e => e.name === '.env')); await assert.rejects(ws.readFile(root,'binary'), /Binary/); assert.deepEqual(await ws.searchFiles(root, 'needle'), [{ path: 'a.txt', line: 2, text: 'needle' }]); });
test('approved write changes a file and reports result to model', async t => { const root = await fixture(t); const events = []; let approvals = 0; await runAgent(options(root, { emit: e => events.push(e), approve: async action => { approvals++; assert.equal(action.before, null); assert.equal(action.args.content, 'hello'); return true; } })); assert.equal(await fs.readFile(path.join(root, 'hello.txt'), 'utf8'), 'hello'); assert.equal(approvals, 1); assert.ok(events.some(e => e.message?.role === 'tool' && e.message.content.includes('Saved'))); });
test('declined writes never touch the filesystem', async t => { const root = await fixture(t); await runAgent(options(root, { approve: async () => false })); await assert.rejects(fs.stat(path.join(root, 'hello.txt')), { code: 'ENOENT' }); });
test('read-only agent rejects a hallucinated write tool', async t => { const root = await fixture(t); let asked = false; const events = []; await runAgent(options(root, { agent: { system: 'Review', mode: 'read' }, approve: async () => { asked = true; return true; }, emit: e => events.push(e) })); assert.equal(asked, false); assert.ok(events.some(e => e.message?.content?.includes('not allowed'))); await assert.rejects(fs.stat(path.join(root, 'hello.txt'))); });
test('concurrent edits invalidate an approval', async t => { const root = await fixture(t); const events = []; await fs.writeFile(path.join(root, 'hello.txt'), 'old'); await runAgent(options(root, { emit: e => events.push(e), approve: async () => { await fs.writeFile(path.join(root, 'hello.txt'), 'user edit'); return true; } })); assert.equal(await fs.readFile(path.join(root, 'hello.txt'), 'utf8'), 'user edit'); assert.ok(events.some(e => e.message?.content?.includes('changed during review'))); });
test('stop after approval prevents a write', async t => { const root = await fixture(t); const controller = new AbortController(); await assert.rejects(runAgent(options(root, { signal: controller.signal, approve: async () => { controller.abort(); return true; } }))); await assert.rejects(fs.stat(path.join(root, 'hello.txt'))); });
test('tool loop is bounded', async t => { const root = await fixture(t); let count = 0; await assert.rejects(runAgent(options(root, { complete: async () => { count++; return toolCall('list_files', { path: '.' }); } })), /12-step/); assert.equal(count, 12); });
test('commands use project cwd and exclude inherited API secrets', async t => { const root = await fixture(t); process.env.AGENT_STUDIO_TEST_SECRET = 'must-not-leak'; t.after(() => delete process.env.AGENT_STUDIO_TEST_SECRET); const result = await ws.runCommand(root, 'pwd; printenv AGENT_STUDIO_TEST_SECRET'); assert.ok(result.output.includes(root)); assert.ok(!result.output.includes('must-not-leak')); });
test('store persists projects, custom agents and conversations', async t => { const root = await fixture(t); const store = new Store(root, root); store.data.conversations.push({ id: 'test', messages: [{ role: 'user', content: 'hello' }] }); store.save(); const loaded = new Store(root); assert.equal(loaded.get('conversations', 'test').messages[0].content, 'hello'); assert.equal(loaded.data.agents.length, 4); assert.equal((await fs.stat(store.file)).mode & 0o777, 0o600); });
test('broken workspace is preserved rather than overwritten', async t => { const root = await fixture(t); await fs.writeFile(path.join(root,'workspace.json'), '{bad'); assert.throws(() => new Store(root), /Cannot read workspace/); assert.equal(await fs.readFile(path.join(root,'workspace.json'),'utf8'), '{bad'); });
test('unavailable keyring stores secrets only in memory', async t => { const root = await fixture(t); const safe = { isEncryptionAvailable: () => true, getSelectedStorageBackend: () => 'basic_text' }; const vault = new Vault(root, safe); vault.set('example','test-fixture-key'); assert.equal(vault.get({ id: 'example' }), 'test-fixture-key'); assert.ok(!(await fs.readFile(vault.file,'utf8')).includes('test-fixture-key')); assert.equal(new Vault(root,safe).get({ id: 'example' }), ''); });
test('keyring encrypts and restores stored keys', async t => { const root = await fixture(t); const safe = { isEncryptionAvailable: () => true, getSelectedStorageBackend: () => 'gnome_libsecret', encryptString: x => Buffer.from(x.split('').reverse().join('')), decryptString: x => x.toString().split('').reverse().join('') }; const vault = new Vault(root, safe); vault.set('example','fixture-key'); assert.equal(new Vault(root,safe).get({ id: 'example' }), 'fixture-key'); assert.ok(!(await fs.readFile(vault.file,'utf8')).includes('fixture-key')); });
