const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { createServer } = require('node:http');
const { normalizeSettings, DEFAULT_SETTINGS } = require('../src/core/settings.cjs');
const { Store } = require('../src/core/store.cjs');
const { McpManager, validateServer, validateSecrets } = require('../src/core/mcp.cjs');
const { runAgent } = require('../src/core/agent.cjs');
async function fixture(t) { const root = await fs.mkdtemp(path.join(os.tmpdir(),'studio-features-')); t.after(() => fs.rm(root,{recursive:true,force:true})); return root; }
const fixtureServer = id => ({ id, name: 'Fixture MCP', transport: 'stdio', command: process.execPath, args: [path.join(__dirname,'fixtures/mcp-server.cjs')] });
function manager(t, root, secrets = new Map()) { const m = new McpManager({ vault: { get: ({id}) => secrets.get(id) || '' }, cwd: root }); t.after(() => m.close()); return m; }
const answer = { role: 'assistant', content: 'Done.' };
function call(name,args={text:'hello'}) { return { role:'assistant', content:null, tool_calls:[{id:'external-1',type:'function',function:{name,arguments:JSON.stringify(args)}}]}; }
test('appearance settings validate all persisted values', () => { assert.deepEqual(normalizeSettings({theme:'invalid',chatFontSize:999,interfaceScale:NaN}),DEFAULT_SETTINGS); const saved=normalizeSettings({theme:'dark',chatFontSize:20,codeFontSize:18,fontFamily:'mono',sendShortcut:'mod-enter',startScreen:'workspace',interfaceScale:125,reducedMotion:true}); assert.equal(saved.theme,'dark');assert.equal(saved.chatFontSize,20);assert.equal(saved.interfaceScale,125);assert.equal(saved.reducedMotion,true); });
test('v1 migration preserves history and adds preferences once', async t => { const root=await fixture(t); const old={version:1,providers:[],projects:[],agents:[{id:'custom',name:'Mine'}],conversations:[{id:'old-chat',messages:[{role:'user',content:'keep me'}]}]};await fs.writeFile(path.join(root,'workspace.json'),JSON.stringify(old));const store=new Store(root);assert.equal(store.data.version,2);assert.equal(store.data.conversations[0].messages[0].content,'keep me');assert.ok(store.data.agents.some(a=>a.id==='custom'));assert.equal(store.data.settings.startScreen,'chat');assert.deepEqual(store.data.mcpServers,[]);store.data.settings.theme='dark';store.save();const again=new Store(root);assert.equal(again.data.settings.theme,'dark');assert.equal(again.data.agents.filter(a=>a.id==='chat').length,1); });
test('standalone chat sends no file or shell tools', async () => { let offered; await runAgent({provider:{},model:'fixture',agent:{mode:'edit',system:'Chat'},messages:[{role:'user',content:'hello'}],signal:new AbortController().signal,emit(){},approve:async()=>true,complete:async request=>{offered=request.tools;return answer;}});assert.deepEqual(offered,[]); });
test('MCP configurations require safe endpoints and literal argument arrays', () => { assert.throws(()=>validateServer({name:'Bad',transport:'http',url:'http://example.com/mcp'}),/HTTPS/);assert.throws(()=>validateServer({name:'Bad',transport:'stdio',command:'node',args:'script.js'}),/array/);assert.throws(()=>validateSecrets({TOKEN:23}),/string/);assert.equal(validateServer({name:'Local',transport:'http',url:'http://localhost:3456/mcp'}).url,'http://localhost:3456/mcp'); });
test('MCP connects to a real stdio server, discovers and calls tools', async t => { const root=await fixture(t);const m=manager(t,root);await m.connect(fixtureServer('stdio'));assert.equal(m.status('stdio').status,'connected');assert.equal(m.status('stdio').tools.length,2);const tool=m.toolSet().find(t=>t.remoteName==='echo_text');assert.match(tool.definition.function.name,/^mcp_[a-f0-9]{32}$/);assert.equal((await tool.call({text:'hello'},new AbortController().signal)).content,'MCP says: hello');await m.disconnect('stdio');assert.deepEqual(m.toolSet(),[]); });
test('MCP credentials do not enter state or inherited environment', async t => { const root=await fixture(t);process.env.EXPLABS_API_KEY='parent-secret-fixture';t.after(()=>delete process.env.EXPLABS_API_KEY);const secrets=new Map([['mcp:secure',JSON.stringify({FIXTURE_TOKEN:'child-secret-fixture'})]]);const m=manager(t,root,secrets);await m.connect(fixtureServer('secure'));const result=await m.toolSet().find(t=>t.remoteName==='secret_status').call({},new AbortController().signal);assert.equal(result.content,'token=[redacted]; inherited=none');assert.ok(!JSON.stringify(m.status('secure')).includes('child-secret-fixture')); });
test('external calls require approval even in standalone chat', async t => { const root=await fixture(t);const m=manager(t,root);await m.connect(fixtureServer('approval'));const tools=m.toolSet();let step=0,approved=0;const events=[];await runAgent({provider:{},agent:{mode:'edit',system:'Chat'},model:'fixture',messages:[],externalTools:tools,signal:new AbortController().signal,emit:e=>events.push(e),approve:async action=>{approved++;assert.equal(action.name,'mcp_call');assert.equal(action.toolName,'echo_text');return true;},complete:async()=>step++?answer:call(tools[0].definition.function.name)});assert.equal(approved,1);assert.ok(events.some(e=>e.message?.content?.includes('MCP says: hello'))); });
test('declined and read-only MCP calls never invoke the server', async t => { const root=await fixture(t);const trace=path.join(root,'calls.txt');const secrets=new Map([['mcp:denied',JSON.stringify({TRACE_PATH:trace})]]);const m=manager(t,root,secrets);await m.connect(fixtureServer('denied'));const tools=m.toolSet();for(const mode of ['edit','read']){let step=0;await runAgent({provider:{},agent:{mode,system:'Test'},model:'fixture',messages:[],externalTools:tools,signal:new AbortController().signal,emit(){},approve:async()=>false,complete:async()=>step++?answer:call(tools[0].definition.function.name)});}await assert.rejects(fs.stat(trace),{code:'ENOENT'}); });
test('MCP Streamable HTTP supports bearer authentication', async t => {const root=await fixture(t);const http=createServer(async(req,res)=>{if(req.method!=='POST'){res.writeHead(405);return res.end();}assert.equal(req.headers.authorization,'Bearer http-fixture-token');const chunks=[];for await(const c of req)chunks.push(c);const q=JSON.parse(Buffer.concat(chunks));if(!('id'in q)){res.writeHead(202);return res.end();}let result;if(q.method==='initialize')result={protocolVersion:q.params.protocolVersion,capabilities:{tools:{}},serverInfo:{name:'http-fixture',version:'1'}};else if(q.method==='tools/list')result={tools:[{name:'hello',inputSchema:{type:'object',properties:{}}}]};else if(q.method==='tools/call')result={content:[{type:'text',text:'Hello over HTTP'}]};else result={};res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({jsonrpc:'2.0',id:q.id,result}));});await new Promise(r=>http.listen(0,'127.0.0.1',r));t.after(()=>{http.closeAllConnections();http.close();});const m=manager(t,root,new Map([['mcp:http','http-fixture-token']]));await m.connect({id:'http',name:'HTTP',transport:'http',url:`http://127.0.0.1:${http.address().port}/mcp`});assert.equal((await m.toolSet()[0].call({},new AbortController().signal)).content,'Hello over HTTP');await m.disconnect('http');});
test('failed MCP processes produce a recoverable connection error', async t => {const root=await fixture(t);const m=manager(t,root);await assert.rejects(m.connect({id:'missing',name:'Missing',transport:'stdio',command:path.join(root,'does-not-exist'),args:[]}));assert.equal(m.status('missing').status,'error');assert.deepEqual(m.toolSet(),[]);});

test('disconnect cancels an MCP handshake and leaves the server disconnected', async t => {const root=await fixture(t);const m=manager(t,root);const config=fixtureServer('cancel');config.args.push('--stall');const connecting=m.connect(config);const rejection=assert.rejects(connecting);await new Promise(r=>setTimeout(r,80));await m.disconnect('cancel');await rejection;assert.equal(m.status('cancel').status,'disconnected');assert.deepEqual(m.toolSet(),[]);});
test('MCP HTTP redirects cannot forward the configured credential', async t => {const root=await fixture(t);let destinationCalls=0;const http=createServer((req,res)=>{if(req.url==='/other')destinationCalls++;res.writeHead(307,{Location:'/other'});res.end();});await new Promise(r=>http.listen(0,'127.0.0.1',r));t.after(()=>{http.closeAllConnections();http.close();});const m=manager(t,root,new Map([['mcp:redirect','fixture-token']]));await assert.rejects(m.connect({id:'redirect',name:'Redirect',transport:'http',url:`http://127.0.0.1:${http.address().port}/mcp`}));assert.equal(destinationCalls,0);});
