const { test } = require('node:test');
const assert = require('node:assert/strict');
const { createServer } = require('node:http');
const { validateBaseUrl, listModels, completion, sseEvents } = require('../src/core/provider.cjs');
async function server(t, handler) { const http = createServer(handler); await new Promise(resolve => http.listen(0, '127.0.0.1', resolve)); t.after(() => new Promise(resolve => { http.closeAllConnections(); http.close(resolve); })); return { baseUrl: `http://127.0.0.1:${http.address().port}/v1` }; }
test('only HTTPS or loopback HTTP endpoints are accepted', () => { assert.equal(validateBaseUrl('https://example.com/v1/'), 'https://example.com/v1'); assert.equal(validateBaseUrl('http://localhost:11434/v1'),'http://localhost:11434/v1'); for (const url of ['http://example.com/v1','file:///tmp/a','https://user:pass@example.com','https://example.com?key=secret']) assert.throws(() => validateBaseUrl(url)); });
test('SSE handles every byte boundary, UTF-8 and CRLF', async () => { const bytes = Buffer.from('data: {"text":"héllo 🌱"}\r\n\r\ndata: [DONE]\r\n\r\n'); async function* chunks() { for (const byte of bytes) yield Buffer.from([byte]); } assert.deepEqual(await Array.fromAsync(sseEvents(chunks())), ['{"text":"héllo 🌱"}','[DONE]']); });
test('model discovery authenticates, sorts and ignores invalid entries', async t => { const provider = await server(t, (req,res) => { assert.equal(req.url,'/v1/models'); assert.equal(req.headers.authorization,'Bearer fixture-key'); res.writeHead(200, {'Content-Type':'application/json'}); res.end(JSON.stringify({ data: [{id:'z'}, {id:'a'}, {}] })); }); assert.deepEqual((await listModels(provider,'fixture-key')).map(x => x.id), ['a','z']); });
test('stream assembles text, tool arguments and usage', async t => { let payload; const provider = await server(t, async (req,res) => { const chunks=[]; for await(const chunk of req) chunks.push(chunk); payload=JSON.parse(Buffer.concat(chunks)); res.writeHead(200, {'Content-Type':'text/event-stream'}); const packets=[{choices:[{delta:{content:'Hello '}}]},{choices:[{delta:{content:'world',tool_calls:[{index:0,id:'call1',function:{name:'read_file',arguments:'{"pa'}}]}}]},{choices:[{delta:{tool_calls:[{index:0,function:{arguments:'th":"a.txt"}'}}]},finish_reason:'tool_calls'}]},{choices:[],usage:{total_tokens:12}}]; for(const packet of packets) res.write(`data: ${JSON.stringify(packet)}\n\n`); res.end('data: [DONE]\n\n'); }); let content=''; const result=await completion({provider,key:'fixture',model:'model-a',messages:[{role:'user',content:'hello'}],onDelta:x=>content+=x}); assert.equal(content,'Hello world'); assert.equal(result.tool_calls[0].function.arguments,'{"path":"a.txt"}'); assert.equal(result.usage.total_tokens,12); assert.equal(payload.model,'model-a'); assert.equal(payload.stream,true); assert.equal(payload.temperature,undefined); });
test('JSON-only compatible servers are supported', async t => { const provider=await server(t,(_req,res)=>{res.writeHead(200,{'Content-Type':'application/json'});res.end(JSON.stringify({choices:[{message:{role:'assistant',content:'ok'}}]}));}); assert.equal((await completion({provider,model:'fixture',messages:[]})).content,'ok'); });
test('provider errors redact API keys and surface rate limits', async t => { const provider=await server(t,(_req,res)=>{res.writeHead(429,{'Content-Type':'application/json'});res.end(JSON.stringify({error:{message:'rate limited fixture-key'}}));}); await assert.rejects(listModels(provider,'fixture-key'), error => error.message.includes('429') && !error.message.includes('fixture-key')); });
test('redirects cannot forward provider credentials', async t => { const provider=await server(t,(_req,res)=>{res.writeHead(302,{Location:'https://example.com'});res.end();}); await assert.rejects(listModels(provider,'fixture-key')); });
test('truncated stream fails clearly', async t => { const provider=await server(t,(_req,res)=>{res.writeHead(200,{'Content-Type':'text/event-stream'});res.end('data: {"choices":[{"delta":{"content":"partial"}}]}\n\n');}); await assert.rejects(completion({provider,model:'fixture',messages:[]}), /ended early/); });
test('requests can be cancelled', async t => { const provider=await server(t,()=>{}); const controller=new AbortController(); controller.abort(); await assert.rejects(completion({provider,model:'fixture',messages:[],signal:controller.signal})); });
