function renderComputer() {
  const info=state.computer || {status:'disconnected'};
  $('#computer-mode').classList.toggle('active',view==='workspace' && computerMode);
  const panel=$('#computer-panel');panel.hidden=!computerMode;
  $('#computer-stop-global')?.remove();
  if(info.status==='connected'||info.status==='connecting'){
    const stop=document.createElement('button');stop.id='computer-stop-global';stop.className='computer-stop';stop.textContent=info.status==='connected'?'■ Stop sharing':'Cancel sharing';stop.onclick=safely(async()=>{state=await api('disconnect-computer');render();});$('.header-actions').prepend(stop);
  }
  if(!computerMode){ if(window.standardChatActions) $('#chat-quick-actions').innerHTML=window.standardChatActions; return; }
  if(!window.standardChatActions)window.standardChatActions=$('#chat-quick-actions').innerHTML;
  const ready=info.status==='connected',connecting=info.status==='connecting';
  const enabled=provider()?.tools!==false && state.agents.find(a=>a.id===agentId)?.mode==='edit';
  panel.innerHTML=`<div class="computer-panel-heading"><span class="computer-orb">▣</span><div><strong>Your computer, with you in control.</strong><p>${ready?'Screen sharing is active. Desktop actions and screenshots ask for approval.':'Run terminal tasks without a project. Connect a screen for visual desktop tasks.'}</p></div><span class="computer-status ${ready?'live':''}">${ready?'● Connected':connecting?'Waiting for permission':'Screen disconnected'}</span></div><div class="computer-capabilities"><span>⌘ Terminal <b>${enabled?'Available':'Enable tools'}</b></span><span>▣ Screen <b>${ready?'Connected':'Optional'}</b></span><span>↖ Mouse & keyboard <b>${ready?'Connected':'Optional'}</b></span></div><div class="computer-actions"><button id="connect-computer" class="${ready?'secondary':'primary'}" ${connecting||busy?'disabled':''}>${ready?'Disconnect screen':connecting?'Check your desktop permission dialog…':'Connect screen'}</button><small>Share one monitor through your Linux permission dialog. Requires an image-capable model for visual tasks.</small></div>${info.error?`<p class="mcp-error">${esc(info.error)}</p>`:''}${!enabled?'<div class="info-note">Choose an agent with editing access and enable “Allow agent tools” in Providers → Configure. <button id="enable-computer-tools" class="text-link">Enable tools for this connection</button></div>':''}<details class="computer-setup"><summary>Setup & privacy</summary><p>Desktop sharing requires Python 3, PyGObject, GStreamer with PipeWire, and a desktop implementing the Remote Desktop portal. Screenshots go to the selected model only when approved; they are not saved in conversation history. Stop sharing disconnects the screen and stops the current run.</p><p>Ubuntu / Debian dependencies:</p><code>sudo apt install python3-gi gir1.2-gstreamer-1.0 gstreamer1.0-pipewire gstreamer1.0-plugins-good</code></details>`;
  $('#enable-computer-tools')?.addEventListener('click',safely(async()=>{if(busy)return;const p=provider();if(!p)return showView('providers');state=await api('save-provider',{...p,tools:true});agentId=state.agents.find(a=>a.id==='chat')?.id || agentId;render();}));
  $('#connect-computer').onclick=safely(async()=>{if(ready){state=await api('disconnect-computer');render();return;}modal('<div class="eyebrow">COMPUTER ACCESS</div><h2>Connect your screen</h2><p>Linux will ask you to choose a monitor and allow keyboard and mouse control. Screenshots can contain information from other apps and are sent to your selected model only after approval.</p><p>Each desktop action asks for approval. You can disconnect at any time using Stop sharing.</p><div class="modal-actions"><button data-close class="secondary">Cancel</button><span></span><button id="confirm-computer" class="primary">Continue to screen sharing</button></div>');$('#confirm-computer').onclick=safely(async()=>{closeModal();try{state=await api('connect-computer');}finally{state=await api('state');render();}});});
  $('#header-view').textContent=view==='workspace'?'Computer':$('#header-view').textContent;
  $('#header-project').textContent=view==='workspace'?'No project required':$('#header-project').textContent;
  $('#welcome-title').innerHTML='A little help.<br><em>Across your whole computer.</em>';
  $('#welcome-description').textContent='Check your setup, work with desktop apps, or run a command. Describe the outcome; review the actions along the way.';
  $('#chat-quick-actions').innerHTML='<button data-chat-prompt="Use the terminal tool to show my Linux version and current working directory."><strong>Check my computer</strong><small>Start with a terminal task</small></button><button data-chat-prompt="Take a screenshot and describe the app currently on my shared screen."><strong>Understand my screen</strong><small>Connect a screen first</small></button><button data-chat-prompt="Help me diagnose Git and SSH authentication. Use tools for safe checks; do not read private keys."><strong>Diagnose my setup</strong><small>Review each command</small></button>';
  $('#prompt').placeholder='What would you like to do on your computer?';
  $('#permission-caption').textContent=enabled?'Computer mode · terminal and desktop actions require approval':'Computer mode · enable agent tools to take actions';
}
function computerApproval(event){
  const capture=event.name==='computer_screenshot';
  modal(`<div class="modal-heading"><div><div class="eyebrow">COMPUTER APPROVAL</div><h2>${capture?'Share a screenshot with your model?':'Review desktop action'}</h2></div><span class="tag">${capture?'Screen capture':'Mouse / keyboard'}</span></div><p>${capture?'Captures your shared monitor and sends the image to the model for this run. It is not saved in chat history.':'Studio will minimize before applying this action to your desktop. Check that the intended app is behind Studio.'}</p>${capture?'':`<pre class="command-review">${esc(JSON.stringify(event.args,null,2))}</pre>`}<div class="modal-actions"><button id="deny-action" class="secondary">Decline</button><span></span><button id="allow-action" class="primary">${capture?'Share screenshot':'Approve action'}</button></div>`);
  $('#allow-action').onclick=safely(()=>api('approve',{id:event.id,accepted:true}));$('#deny-action').onclick=safely(()=>api('approve',{id:event.id,accepted:false}));
}
